baseurl = "https://你的博客域名/"
languageCode = "zh-cn"
title = "秋贤的博客"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

[params]
  # 侧边栏副标题
  subtitle = "记录生活与思考"

  [params.footer]
    since = 2024
    customText = "© 秋贤的博客"

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/你的GitHub用户名"
    icon = "github"

# 分页设置
[pagination]
  pagerSize = 5
