baseurl = "https://blog.qiuxianli.dpdns.org/"
languageCode = "zh-cn"
title = "秋贤的博客"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
favicon = "static/images/薇古丝头像.jpg"

[params]
  # 侧边栏副标题
  subtitle = "记录生活与思考"

  [params.footer]
    since = 2024
    customText = "© 秋贤的博客"

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/QiuXianL"
    icon = "github"

# 分页设置
[pagination]
  pagerSize = 5
