# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/QiuXianL"
[social.params]
icon = "brand-github"

[[social]]
identifier = "qq"
name = "QQ"
url = "https://wpa.qq.com/msgrd?v=3&uin=162211800&site=qq&menu=yes"
[social.params]
icon = "message"
